import { describe, it, expect } from "vitest";
import { readFileSync, writeFileSync, mkdtempSync, rmSync, copyFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { generate, parseModel } from "./generate";

const fixturePath = fileURLToPath(new URL("./__fixtures__/sample.g.ts", import.meta.url));
const fixture = readFileSync(fixturePath, "utf-8");

describe("generate", () => {
  it("生成产物包含 auto-generated 头部和 import 语句", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.content).toContain("// <auto-generated/>");
    expect(result.content).toContain('import type { MockHandler } from "@tkwf/tsclient-mock"');
    expect(result.content).toContain('import { createMockDb, defineMock } from "@tkwf/tsclient-mock"');
  });

  it("生成产物包含所有 field 的 handler（覆盖率保证）", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.fieldCount).toBe(6);

    expect(result.content).toContain("paymentLogs:");
    expect(result.content).toContain("paymentLog:");
    expect(result.content).toContain("merchant:");
    expect(result.content).toContain("createPaymentLog:");
    expect(result.content).toContain("updatePaymentLog:");
    expect(result.content).toContain("deletePaymentLog:");
  });

  it("生成产物包含 satisfies 约束和 _AssertAllFieldsCovered", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.content).toContain("satisfies Record<keyof typeof Query | keyof typeof Mutation, MockHandler>");
    expect(result.content).toContain("_AssertAllFieldsCovered");
    expect(result.content).toContain("Exclude<_AllFields, keyof typeof handlers>");
  });

  it("生成产物包含 createMockDb 和表名", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.content).toContain("createMockDb({");
    expect(result.content).toContain("paymentLogs: []");
    expect(result.content).toContain("merchants: []");
  });

  it("生成产物包含 DTO schema 常量", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.content).toContain("PaymentLogSchema");
    expect(result.content).toContain("MerchantSchema");
    expect(result.content).toContain('kind: "number", isId: true');
    expect(result.content).toContain('kind: "enum", enumValues: []');
  });

  it("query + Connection 返回生成 db.query 调用", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.content).toContain('db.query("paymentLogs"');
    expect(result.content).toContain("vars?.where");
    expect(result.content).toContain("vars?.order");
  });

  it("query + 单实体生成 db.queryOne 调用", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.content).toContain('db.queryOne("paymentLogs"');
  });

  it("mutation + input 生成 db.insert 调用", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.content).toContain('db.insert("paymentLogs"');
    expect(result.content).toContain("vars?.input");
  });

  it("update 类 mutation 生成 db.update 调用", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.content).toContain('db.update<');
    expect(result.content).toContain('("paymentLogs"');
    expect(result.content).toContain("vars?.input");
  });

  it("delete 类 mutation 生成 db.remove 调用", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.content).toContain('db.remove("paymentLogs"');
  });

  it("统计信息正确", () => {
    const result = generate(fixture, fixturePath, fixturePath.replace("sample.g.ts", "sample.mock.g.ts"));
    expect(result.fieldCount).toBe(6);
    expect(result.dtoCount).toBe(2);
  });

  it("parseModel 返回正确结构的中间模型", () => {
    const model = parseModel(fixture);
    expect(model.parsedDoc.fields.length).toBeGreaterThan(0);
    expect(model.serviceMethods.length).toBe(6);
    expect(Object.keys(model.dtoSchemas)).toContain("PaymentLog");
    expect(Object.keys(model.dtoSchemas)).toContain("Merchant");
  });

  it("生成产物在 nodenext 消费端可编译（import 带 .js 扩展名）", () => {
    // 前置条件：dist 已构建（npm run build）
    const repoRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
    const mockDist = join(repoRoot, "dist", "index.d.ts");
    const clientDist = join(repoRoot, "node_modules", "@tkwf", "tsclient", "dist", "index.d.ts");
    if (!existsSync(mockDist) || !existsSync(clientDist)) {
      throw new Error("前置条件缺失：请先 npm run build（dist/ 与 @tkwf/tsclient dist 需存在）");
    }

    // 临时目录：fixture + 生成产物 + nodenext tsconfig
    const tmpDir = mkdtempSync(join(tmpdir(), "mockgen-"));
    try {
      const srcPath = join(tmpDir, "sample.g.ts");
      const outPath = join(tmpDir, "sample.mock.g.ts");
      copyFileSync(fixturePath, srcPath);
      const result = generate(fixture, srcPath, outPath);
      writeFileSync(outPath, result.content);
      // 模拟真实 Vite/ESM 消费端：type: module
      writeFileSync(join(tmpDir, "package.json"), JSON.stringify({ type: "module" }));

      const tsconfigPath = join(tmpDir, "tsconfig.json");
      writeFileSync(
        tsconfigPath,
        JSON.stringify({
          compilerOptions: {
            target: "es2023",
            module: "nodenext",
            moduleResolution: "nodenext",
            strict: true,
            skipLibCheck: true,
            noEmit: true,
            verbatimModuleSyntax: true,
            paths: {
              "@tkwf/tsclient-mock": [mockDist],
              "@tkwf/tsclient": [clientDist],
            },
          },
          include: ["*.ts"],
        }, null, 2),
      );

      const tscBin = join(repoRoot, "node_modules", "typescript", "bin", "tsc");
      const run = spawnSync(process.execPath, [tscBin, "-p", tsconfigPath], {
        encoding: "utf-8",
        timeout: 60_000,
      });
      expect(run.status, `tsc 输出:\n${run.stdout}\n${run.stderr}`).toBe(0);
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});