/**
 * 生成产物模板字符串。
 * 不涉及逻辑判断，只提供模板片段。
 */

import type { MockFieldSchema } from "../factory.js";

/**
 * 头部自动生成注释。
 */
export function header(): string {
  return [
    "// <auto-generated/> by @tkwf/tsclient-mock gen-mock-handlers",
    "// 修改会丢失：编辑源文件后重新生成",
    "",
  ].join("\n");
}

/**
 * import 语句。
 * @param importPath 源 ts-client.g.ts 的相对路径（如 "./ts-client.g"）
 */
export function imports(importPath: string, typeNames: string[]): string {
  const typeImports = typeNames.filter(Boolean);
  const lines: string[] = [
    'import type { MockHandler, ScenarioConfig } from "@tkwf/tsclient-mock";',
    'import { createMockDb, defineMock } from "@tkwf/tsclient-mock";',
  ];
  if (typeImports.length > 0) {
    lines.push(`import type { ${typeImports.join(", ")} } from "${importPath}";`);
  }
  lines.push("");
  return lines.join("\n");
}

/**
 * 内存数据库骨架。
 * @param tableInits 表名 → 空数组初始化的映射
 */
export function dbSkeleton(tableInits: Record<string, string>): string {
  const entries = Object.entries(tableInits)
    .map(([table, type]) => `  ${table}: [] satisfies ${type}[]`)
    .join(",\n");
  return [
    "// ── 内存数据库（骨架，Agent 填充初始数据） ──",
    `export const db = createMockDb({\n${entries},\n});`,
    "",
  ].join("\n");
}

/**
 * 场景数据集骨架。
 * 生成 default 和 empty 两个数据集，每个数据集包含所有表的空数组。
 * @param tableInits 表名 → 实体类型名的映射
 */
export function scenariosSkeleton(tableInits: Record<string, string>): string {
  const entries = Object.entries(tableInits).map(([table, type]) => {
    if (!type || type === "unknown") {
      return `    ${table}: [] /* TODO: 无实体类型，Agent 自行填充 */`;
    }
    return `    ${table}: [] satisfies ${type}[]`;
  });
  const block = entries.join(",\n");
  return [
    "// ── 场景数据集骨架（数据留 Agent 填充） ──",
    "export const scenarios = {",
    "  default: {",
    block,
    "  },",
    "  empty: {",
    block,
    "  },",
    "};",
    "",
  ].join("\n");
}

/**
 * 场景注入配置骨架。
 * 生成 error 和 loading 两个场景的注入配置骨架。
 */
export function scenarioOverridesSkeleton(): string {
  return [
    "// ── 场景注入配置骨架 ──",
    'export const scenarioOverrides: Record<string, ScenarioConfig> = {',
    '  error: { fieldOptions: { /* TODO: Agent 按 field 填 error / failRate */ } },',
    '  loading: { delayMs: 3000 },',
    "};",
    "",
  ].join("\n");
}

/**
 * DTO schema 常量。
 */
export function dtoTypeSchemas(dtos: Array<{ name: string; schema: string }>): string {
  if (dtos.length === 0) return "";
  const blocks = dtos
    .map((d) => `export const ${d.name}Schema = ${d.schema} as const;`)
    .join("\n");
  return [
    "// ── DTO → factory 配置（骨架，Agent 可按需调整） ──",
    blocks,
    "",
  ].join("\n");
}

/**
 * 生成单个 DTO 的 schema 对象字面量字符串。
 * 递归处理嵌套字段。
 */
export function schemaLiteral(
  fields: Record<string, MockFieldSchema>,
  indent: string,
): string {
  const lines: string[] = ["{"];
  for (const [key, value] of Object.entries(fields)) {
    const comma = key === Object.keys(fields).at(-1) ? "" : ",";
    switch (value.kind) {
      case "string":
        lines.push(`${indent}  ${key}: { kind: "string"${value.isId ? ', isId: true' : ''} }${comma}`);
        break;
      case "number":
        lines.push(`${indent}  ${key}: { kind: "number"${value.isId ? ', isId: true' : ''} }${comma}`);
        break;
      case "boolean":
        lines.push(`${indent}  ${key}: { kind: "boolean" }${comma}`);
        break;
      case "date":
        lines.push(`${indent}  ${key}: { kind: "date" }${comma}`);
        break;
      case "enum":
        lines.push(`${indent}  ${enumTodoComment()}`);
        lines.push(`${indent}  ${key}: { kind: "enum", enumValues: [] }${comma}`);
        break;
      case "array":
        lines.push(`${indent}  ${key}: { kind: "array", element: ${schemaLiteralElement(value.element, indent + "  ")} }${comma}`);
        break;
      case "object":
        if (value.fields && Object.keys(value.fields).length > 0) {
          lines.push(`${indent}  ${key}: { kind: "object", fields: ${schemaLiteral(value.fields, indent + "  ")} }${comma}`);
        } else {
          lines.push(`${indent}  ${key}: { kind: "object", fields: {} }${comma}`);
        }
        break;
      default:
        lines.push(`${indent}  ${key}: { kind: "string" }${comma}`);
    }
  }
  lines.push(`${indent.slice(0, -2)}}`);
  return lines.join("\n");
}

function schemaLiteralElement(
  element: MockFieldSchema | undefined,
  indent: string,
): string {
  if (!element) return '{ kind: "string" }';
  switch (element.kind) {
    case "string":
      return `{ kind: "string"${element.isId ? ', isId: true' : ''} }`;
    case "number":
      return `{ kind: "number"${element.isId ? ', isId: true' : ''} }`;
    case "boolean":
      return '{ kind: "boolean" }';
    case "date":
      return '{ kind: "date" }';
    case "enum":
      return '{ kind: "enum", enumValues: [] }';
    case "array":
      return `{ kind: "array", element: ${schemaLiteralElement(element.element, indent)} }`;
    case "object":
      if (element.fields && Object.keys(element.fields).length > 0) {
        return `{ kind: "object", fields: ${schemaLiteral(element.fields, indent)} }`;
      }
      return '{ kind: "object", fields: {} }';
    default:
      return '{ kind: "string" }';
  }
}

/**
 * 生成 handler 的 defineMock 包装。
 * @param fieldName field 名
 * @param argsTypeName args 类型名（如 "PaymentLogsArgs"）
 * @param returnTypeName 返回类型名（如 "PaymentLogConnection"）
 * @param body handler 函数体
 */
export function handlerBlock(
  fieldName: string,
  argsTypeName: string | undefined,
  returnTypeName: string,
  body: string,
  comment?: string,
): string {
  const lines: string[] = [];
  if (comment) {
    lines.push(`  // ${fieldName}${comment}`);
  } else {
    lines.push(`  // ${fieldName}`);
  }
  lines.push(`  ${fieldName}: defineMock<{`);
  lines.push(`    field: "${fieldName}";`);
  if (argsTypeName) {
    lines.push(`    args: ${argsTypeName};`);
  }
  lines.push(`    result: ${returnTypeName};`);
  lines.push(`  }>((vars) => {`);
  lines.push(`    ${body}`);
  lines.push(`  }),`);
  return lines.join("\n");
}

/**
 * 生成 handlers 对象的 satisfies 约束。
 */
export function handlersSatisfies(): string {
  return [
    "} satisfies Record<keyof typeof Query | keyof typeof Mutation, MockHandler>;",
    "",
  ].join("\n");
}

/**
 * 生成 _AssertAllFieldsCovered 编译期覆盖检查。
 */
export function assertAllFieldsCovered(): string {
  return [
    "// ── 完整性覆盖检查：新增 field 缺 handler → 编译报错 ──",
    "type _AllFields = keyof typeof Query | keyof typeof Mutation;",
    "type _AssertAllFieldsCovered = [Exclude<_AllFields, keyof typeof handlers>] extends [never] ? true : never;",
    "const _check: _AssertAllFieldsCovered = true;",
    "",
  ].join("\n");
}

/**
 * 枚举字段 TODO 注释。
 */
export function enumTodoComment(): string {
  return "// TODO: 枚举值需 Agent 填充（codegen 无 enum 声明）";
}

/**
 * 反向分页 TODO 注释。
 */
export function reversePaginationTodo(): string {
  return "// TODO: 反向分页未实现，Agent 需自定义 last/before 处理";
}

/**
 * 待 Agent 填充注释。
 */
export function agentFillTodo(): string {
  return "// TODO: 待 Agent 填充";
}

/**
 * id 提取 TODO 注释。
 */
export function idExtractionTodo(): string {
  return "// TODO: id 从 args 提取，需 Agent 确认 id 字段位置";
}